#DB
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tteoksang
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # (옵션: none, validate, update, create, create-drop)
    show-sql: true  # 실행되는 SQL을 로그로 출력
    properties:
      hibernate:
        format_sql: true  # SQL을 보기 좋게 출력