profile: dev

#DB
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none  # (옵션: none, validate, update, create, create-drop)

# external API
external:
  api:
    crawler: ${EXTERNAL_API_CRAWLER} # tteoksang-crawler fast api
    kis: ${EXTERANL_API_KIS} # 한국투자증권 api

# KIS secret
kis:
  appkey: ${KIS_APPKEY}
  appsecret: ${KIS_APPSECRET}