profile: dev

#DB
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none  # (옵션: none, validate, update, create, create-drop)
